name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: |
          echo "building"
        
      - name: SonarCloud analysis
        run: |
          chmod +x gradlew
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD_JMOLINAE2 }}

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     
      
      - name: Docker Build
        run: | 
          docker build --tag juanmolina31/pet-clinic:latest .
          docker images

      - name: Docker Push
        run: |
          docker push juanmolina31/pet-clinic

  deploy: 
    runs-on: self-hosted 
    needs: build
    steps: 

    - uses: actions/checkout@v3
    
    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yml
