name: CI

on:
  
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: build
        run: |
         echo "building"
  test:
     runs-on: ubuntu-latest
     needs: build 
     steps:
       - name: SonarCloud analisys
         run: |
            chmod +x gradlew
            ./gradlew build sonar -Dsonar.token=${{ secret.TOKEN_SONARCLOUD_JMOLINAE }}
             
         

  
